// Generated by the lark-cli {{.ToolVersion}}.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
package {{.Package}}.iface;

import lark.net.rpc.annotation.RpcMethod;
import lark.net.rpc.annotation.RpcService;
import lark.net.rpc.client.InvokeMode;
import {{.Package}}.dto.{{.Name}}Dto.*;
{{- range .Imports}}
import {{.Path}};
{{- end}}

/**
 * {{.Description}}
 */
@RpcService({{if .Alias}}name = "{{.Alias}}", {{end}}{{if .Fail}}fail = FailMode.{{.Fail}}, {{end}}description = "{{.Description}}")
public interface {{.Name}}Service {
    {{range $i, $m := .Methods}}
    {{- if gt $i 0}}

    {{end -}}
    /**
	 * {{.Description}}
     *
     {{- range $i, $p := .Request}}
     * @param {{.Name}}
     {{- end}}
     {{- if .Response}}
     * @return{{end}}
     */
    @RpcMethod({{if .Alias}}name = "{{.Alias}}", {{end}}{{if .Invoke}}invoke = InvokeMode.{{.Invoke | upper}}, {{end}}description = "{{.Description}}")
    {{if .Response}}{{.Response.Type}}{{else}}void{{end}} {{.Name | camel}}({{if .Request}}{{range $i, $p := .Request}}{{if gt $i 0}}, {{end}}{{.Type}} {{.Name}}{{end}}{{end}});
    {{- end}}
}